name: Format

on:
  pull_request:
    branches: [main]
    paths:
      - "src/**"

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 24.18.0

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm exec prettier --ignore-path .gitignore --check "src/**/*.{js,ts,json,css,tsx,jsx}"
