name: Pre Release Build

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*-*"
  workflow_dispatch:
    inputs:
      draft:
        description: "Create draft release"
        required: false
        default: true
        type: boolean

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - name: Build Pre-release
        run: |
          chmod +x build.sh
          ./build.sh --dev --compress
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Read version and determine tag name
        id: version
        run: |
          version=$(cat dist/VERSION)
          echo "version=$version" >> $GITHUB_OUTPUT

          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "tag_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=rolling" >> $GITHUB_OUTPUT
          fi

      - name: Upload Pre-release Assets
        uses: softprops/action-gh-release@v2
        with:
          name: Pre-release ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.tag_name }}
          # Enforce the naming strategy
          files: dist/openlist-frontend-dist-v*-*.tar.gz
          fail_on_unmatched_files: true
          prerelease: true
          draft: ${{ github.event_name == 'workflow_dispatch' && inputs.draft || false }}

permissions:
  contents: write
